name: Build AMI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-ami:

    # specify runner
    runs-on: ubuntu-latest

    steps:
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Check env
      run: |
        echo $SSH_USERNAME
        echo $SOURCE_AMI
        echo $AWS_REGION
      
      # validate json template
    - name: Validate template
      run: packer validate ami.json
      
      # build ami using packer
    - name: Build AMI using template
      run: packer build ami.json
