name: Build AMI Workflow

on:
  push:
    branches: [ master ]

jobs:
  build-ami:

    # specify runner
    runs-on: ubuntu-latest

    steps:
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
      # validate json template
    - name: Validate template
      run: packer validate ami.json
      
      # build ami using packer
    - name: Build AMI using template
      run: packer build ami.json
