name: Build AMI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-ami:

    # specify runner
    runs-on: ubuntu-latest

    steps:
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
      # validate json template
    - name: Validate template
      env:
        AMI_USERS: ${{ secrets.AMI_USERS }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: packer validate ami.json
      
      # build ami using packer
    - name: Build AMI using template
      env:
        AMI_USERS: ${{ secrets.AMI_USERS }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: packer build ami.json
